import { Geist, Geist_Mono, Varela_Round } from "next/font/google";
import "./globals.css";
import { Metadata } from 'next';



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/* export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export const metadata = {
  title: {
    template: 'Pokemon App by Tej R',
    default: 'Pokemon App by Tej R'
  },
  description: 'Peokemon search and information App '
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Varela+Round&display=swap" rel="stylesheet" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
        {children}
      </body>
    </html >
  );
}
