import { Geist, Geist_Mono, Varela_Round } from "next/font/google";
import "./globals.css";
import { Metadata } from 'next';

const varelaRound = Varela_Round({
  weight: '400',
  subsets: ['latin'],
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/* export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export const metadata = {
  title: {
    template: 'Pokemon App by Janardan B',
    default: 'Pokemon App by Janardan B'
  },
  description: 'Peokemon search and information App '
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={varelaRound.className}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
        {children}
      </body>
    </html >
  );
}
